SQL succeeded but Query is now invalid ('task_editor', 303, 'accept'): 
UPDATE tasks 
SET do = '5',
    priority = 0.0,
    level_id = 0,
    primary_activity_id = NULL,
    secondary_activity_id = NULL,
    space_id = None,
    ilk = 1
    draft = FALSE
WHERE id=373
